name: Python Unit Tests

on:
  push:
    branches: [ main, crypto]
  pull_request:
    branches: [ main, crypto ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Or any specific Python version required by your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        pip install .

    - name: Run unit tests
      run: |
        python -m unittest discover -s src/ml_investing_wne/tests/unit_tests -p 'test*.py'
